### ISSUE TITLE
Issue with gap in MakeFile

### ISSUE THREAD

**Issue by schr4der** [dricottone/dalle-mini-terminal#1]

**Comment by dricottone** [comment]
The Makefile needs to be refactored. Essentially the issue you ran into was: a dev dependency was used in the install recipe. I've gone ahead and made some changes in 3d1904e to address that.

Even so, there are outstanding issues with this program. I'm behind on developments in upstream projects and I won't have time to fix those in the near future. If you are hoping to generate images on the command line using DALL-E, I suggest [this program](https://github.com/kuprel/min-dalle#command-line) instead.

**Comment by dricottone** [comment]
All issues should be solved in [1beb83d](https://github.com/dricottone/dalle-mini-terminal/commit/1beb83d1b0cb623abda74fc54c56a514c6694fe2). The dev dependency is stripped out. Dependencies have been pinned to fix their incompatilbilities. Bear in mind that there are breaking changes to this commit, so please take another look at the README before trying again.
