### ISSUE TITLE
Minimal Dockerfile?

### ISSUE THREAD

**Issue by gwpl** [dricottone/dalle-mini-terminal#2]
Could someone please add minimal Dockerfile (even to run it on CPU) ?

Thank you!

**Comment by dricottone** [comment]
I've added a [Dockerfile](https://github.com/dricottone/dalle-mini-terminal/blob/dev/Dockerfile) in [1beb83d](https://github.com/dricottone/dalle-mini-terminal/commit/1beb83d1b0cb623abda74fc54c56a514c6694fe2). Let me know if you have any issues using it.
